package com.example.soapwebservice.interfaces;

import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.5
 * 2024-11-14T00:55:54.183+02:00
 * Generated source version: 4.0.5
 *
 */
@WebServiceClient(name = "soapWebServiceExampleHttpService",
                  wsdlLocation = "file:/C:/Users/user/Documents/SOAP/soap-to-rest-backend-service/src/main/resources/wsdl/employees.wsdl",
                  targetNamespace = "http://interfaces.soapwebservice.example.com")
public class SoapWebServiceExampleHttpService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://interfaces.soapwebservice.example.com", "soapWebServiceExampleHttpService");
    public static final QName SoapWebServiceExampleHttpSoap11 = new QName("http://interfaces.soapwebservice.example.com", "soapWebServiceExampleHttpSoap11");
    static {
        URL url = null;
        try {
            url = URI.create("file:/C:/Users/user/Documents/SOAP/soap-to-rest-backend-service/src/main/resources/wsdl/employees.wsdl").toURL();
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SoapWebServiceExampleHttpService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/user/Documents/SOAP/soap-to-rest-backend-service/src/main/resources/wsdl/employees.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SoapWebServiceExampleHttpService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SoapWebServiceExampleHttpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapWebServiceExampleHttpService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public SoapWebServiceExampleHttpService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SoapWebServiceExampleHttpService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SoapWebServiceExampleHttpService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns SoapWebServiceExampleHttp
     */
    @WebEndpoint(name = "soapWebServiceExampleHttpSoap11")
    public SoapWebServiceExampleHttp getSoapWebServiceExampleHttpSoap11() {
        return super.getPort(SoapWebServiceExampleHttpSoap11, SoapWebServiceExampleHttp.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoapWebServiceExampleHttp
     */
    @WebEndpoint(name = "soapWebServiceExampleHttpSoap11")
    public SoapWebServiceExampleHttp getSoapWebServiceExampleHttpSoap11(WebServiceFeature... features) {
        return super.getPort(SoapWebServiceExampleHttpSoap11, SoapWebServiceExampleHttp.class, features);
    }

}
