package com.example.soapwebservice.interfaces;

import jakarta.jws.Oneway;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.0.5
 * 2024-11-14T00:55:54.120+02:00
 * Generated source version: 4.0.5
 *
 */
@WebService(targetNamespace = "http://interfaces.soapwebservice.example.com", name = "soapWebServiceExampleHttp")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SoapWebServiceExampleHttp {

    @WebMethod
    @Oneway
    public void getEmployeeById(

        @WebParam(partName = "getEmployeeByIdRequest", name = "getEmployeeByIdRequest", targetNamespace = "http://interfaces.soapwebservice.example.com")
        GetEmployeeByIdRequest getEmployeeByIdRequest
    );

    @WebMethod
    @WebResult(name = "addEmployeeResponse", targetNamespace = "http://interfaces.soapwebservice.example.com", partName = "addEmployeeResponse")
    public AddEmployeeResponse addEmployee(

        @WebParam(partName = "addEmployeeRequest", name = "addEmployeeRequest", targetNamespace = "http://interfaces.soapwebservice.example.com")
        AddEmployeeRequest addEmployeeRequest
    );

    @WebMethod
    @WebResult(name = "updateEmployeeResponse", targetNamespace = "http://interfaces.soapwebservice.example.com", partName = "updateEmployeeResponse")
    public UpdateEmployeeResponse updateEmployee(

        @WebParam(partName = "updateEmployeeRequest", name = "updateEmployeeRequest", targetNamespace = "http://interfaces.soapwebservice.example.com")
        UpdateEmployeeRequest updateEmployeeRequest
    );

    @WebMethod
    @WebResult(name = "deleteEmployeeResponse", targetNamespace = "http://interfaces.soapwebservice.example.com", partName = "deleteEmployeeResponse")
    public DeleteEmployeeResponse deleteEmployee(

        @WebParam(partName = "deleteEmployeeRequest", name = "deleteEmployeeRequest", targetNamespace = "http://interfaces.soapwebservice.example.com")
        DeleteEmployeeRequest deleteEmployeeRequest
    );
}
